name: OpenAI Code Correction

on:
  push:
    branches:
      - main

jobs:
  code-correction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install openai

    - name: Run OpenAI Correction
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python openai_script.py

    - name: Commit Corrected Code
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "OpenAI Correction"
        git push
